"""Velocity Verlet integrator for N-body gravitational simulation.

Units throughout: AU (position), AU/day (velocity), AU³ kg⁻¹ day⁻² (G).
The integrator is fully stateless: arrays in, arrays out.
"""
from __future__ import annotations
import numpy as np
from .exceptions import NumericalIntegrityError

# Convert G from SI to AU³ kg⁻¹ day⁻²
# G_SI = 6.674e-11 m³ kg⁻¹ s⁻²
# 1 AU = 1.495978707e11 m,  1 day = 86400 s
G_AU_DAY: float = 6.674e-11 * (86400.0 ** 2) / (1.495978707e11 ** 3)

#: Softening length (AU) — prevents force singularities at close approach
SOFTENING: float = 1e-4

#: Maximum permitted displacement (AU) for a single sub-step
MAX_DISPLACEMENT_PER_STEP: float = 100.0


class VelocityVerletIntegrator:
    """Symplectic Velocity Verlet integrator.

    Conserves orbital energy far better than plain Euler integration
    over long time spans, making it suitable for multi-year simulations.
    """

    def __init__(
        self,
        softening: float = SOFTENING,
        max_displacement: float = MAX_DISPLACEMENT_PER_STEP,
    ) -> None:
        if softening < 0 or not np.isfinite(softening):
            raise ValueError(f"softening must be non-negative and finite, got {softening}")
        if max_displacement <= 0 or not np.isfinite(max_displacement):
            raise ValueError(f"max_displacement must be positive and finite, got {max_displacement}")
        self.softening = float(softening)
        self.max_displacement = float(max_displacement)

    def _accelerations(
        self, positions: np.ndarray, masses: np.ndarray
    ) -> np.ndarray:
        """Return gravitational accelerations for all bodies.

        Parameters
        ----------
        positions : (N, 3) ndarray — body positions in AU
        masses    : (N,)   ndarray — body masses in kg

        Returns
        -------
        (N, 3) ndarray — accelerations in AU day⁻²
        """
        if not np.all(np.isfinite(positions)):
            raise NumericalIntegrityError("Non-finite coordinates encountered in acceleration calculation.")
        if not np.all(np.isfinite(masses)):
            raise NumericalIntegrityError("Non-finite masses encountered in acceleration calculation.")

        # diff[i, j] = r_j - r_i, shape (N, N, 3)
        diff = positions[np.newaxis, :, :] - positions[:, np.newaxis, :]
        # Squared distance with softening, shape (N, N)
        dist_sq = np.einsum("ijk,ijk->ij", diff, diff) + self.softening ** 2
        dist_cubed = dist_sq ** 1.5
        # factor[i, j] = G * m_j / |r_j - r_i|³
        factor = G_AU_DAY * masses[np.newaxis, :] / dist_cubed
        np.fill_diagonal(factor, 0.0)   # zero out self-interaction
        acc = np.einsum("ij,ijk->ik", factor, diff)
        if not np.all(np.isfinite(acc)):
            raise NumericalIntegrityError("Non-finite accelerations computed.")
        return acc

    def step(
        self,
        positions: np.ndarray,
        velocities: np.ndarray,
        masses: np.ndarray,
        dt: float,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Advance by one timestep dt (days).

        Returns new (positions, velocities), both (N, 3).
        """
        if dt <= 0 or not np.isfinite(dt):
            raise NumericalIntegrityError(f"Step dt must be positive and finite, got {dt}")
        if not np.all(np.isfinite(positions)):
            raise NumericalIntegrityError("Non-finite positions in step input.")
        if not np.all(np.isfinite(velocities)):
            raise NumericalIntegrityError("Non-finite velocities in step input.")

        a0 = self._accelerations(positions, masses)
        new_pos = positions + velocities * dt + 0.5 * a0 * dt ** 2

        # Extreme displacement guard
        if len(positions) > 0:
            disp = np.linalg.norm(new_pos - positions, axis=1)
            if np.any(disp > self.max_displacement):
                max_disp = float(np.max(disp))
                raise NumericalIntegrityError(
                    f"Extreme displacement detected in single step: {max_disp:.2e} AU "
                    f"(limit: {self.max_displacement:.2e} AU)"
                )

        a1 = self._accelerations(new_pos, masses)
        new_vel = velocities + 0.5 * (a0 + a1) * dt

        if not np.all(np.isfinite(new_pos)) or not np.all(np.isfinite(new_vel)):
            raise NumericalIntegrityError("Non-finite state generated by integration step.")

        return new_pos, new_vel
